"""save plan preferences on profile

Revision ID: 7c6c1d3adbe5
Revises: 507ca1a93d57
Create Date: 2026-09-24 22:33:15.231595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c6c1d3adbe5'
down_revision: Union[str, None] = '507ca1a93d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('plan_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'plan_preferences')
    # ### end Alembic commands ###
