"""add attempts to email codes

Revision ID: 5d01c5e0e54d
Revises: 22e45417ed28
Create Date: 2026-09-23 20:18:34.769846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d01c5e0e54d'
down_revision: Union[str, None] = '22e45417ed28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_codes', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_codes', 'attempts')
    # ### end Alembic commands ###
