"""initial schema

Revision ID: 8cbd10c1ed26
Revises: 
Create Date: 2026-09-21 21:05:39.700612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cbd10c1ed26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('muscle_groups', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('secondary_muscle_groups', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('instructions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty in ('beginner','intermediate','advanced')", name='exercises_difficulty_check'),
    sa.CheckConstraint("media_type in ('image','gif')", name='exercises_media_type_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_equipment'), 'exercises', ['equipment'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('generated_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider = 'anthropic'", name='integration_tokens_provider_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'provider')
    )
    op.create_table('measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_type'), 'measurements', ['type'], unique=False)
    op.create_table('progress_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_exercise_feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rating in ('like','dislike','neutral')", name='user_exercise_feedback_rating_check'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'exercise_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('equipment_access', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('unit_system', sa.String(), nullable=False),
    sa.Column('anthropic_api_key_set', sa.Boolean(), nullable=False),
    sa.Column('include_warmup', sa.Boolean(), nullable=False),
    sa.Column('plan_refresh_cadence', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Numeric(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("experience_level in ('beginner','intermediate','advanced')", name='user_profiles_experience_level_check'),
    sa.CheckConstraint("gender in ('male','female','other','prefer_not_to_say')", name='user_profiles_gender_check'),
    sa.CheckConstraint("goal in ('strength','hypertrophy','general_fitness','endurance')", name='user_profiles_goal_check'),
    sa.CheckConstraint("plan_refresh_cadence in ('weekly','biweekly','monthly')", name='user_profiles_plan_refresh_cadence_check'),
    sa.CheckConstraint("unit_system in ('metric','imperial')", name='user_profiles_unit_system_check'),
    sa.CheckConstraint('birth_year between 1900 and 2100', name='user_profiles_birth_year_check'),
    sa.CheckConstraint('height_cm between 50 and 300', name='user_profiles_height_cm_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('perceived_exertion', sa.SmallInteger(), nullable=True),
    sa.Column('felt_rating', sa.String(), nullable=True),
    sa.Column('enjoyed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("felt_rating in ('too_easy','just_right','too_hard')", name='workouts_felt_rating_check'),
    sa.CheckConstraint("source = 'manual'", name='workouts_source_check'),
    sa.CheckConstraint('perceived_exertion between 1 and 10', name='workouts_perceived_exertion_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='workouts_user_source_external_id_key')
    )
    op.create_table('personal_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('best_weight_kg', sa.Numeric(), nullable=False),
    sa.Column('best_weight_reps', sa.Integer(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id', 'exercise_id')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('exercise_name_raw', sa.String(), nullable=True),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Numeric(), nullable=True),
    sa.Column('rpe', sa.Numeric(), nullable=True),
    sa.CheckConstraint('rpe between 0 and 10', name='workout_sets_rpe_check'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sets_exercise_id'), 'workout_sets', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_sets_workout_id'), 'workout_sets', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sets_workout_id'), table_name='workout_sets')
    op.drop_index(op.f('ix_workout_sets_exercise_id'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_table('personal_records')
    op.drop_table('workouts')
    op.drop_table('user_profiles')
    op.drop_table('user_exercise_feedback')
    op.drop_table('progress_photos')
    op.drop_index(op.f('ix_measurements_type'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('integration_tokens')
    op.drop_table('generated_plans')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
